### ISSUE TITLE
auth-tokens-refresh (and possibly other functions) failing on current Docker image

### ISSUE THREAD

**Issue by mwvaughn** [iPlantCollaborativeOpenSource/cyverse-sdk#1]
Upon further testing of the new alpine:3.3-based `iplantc/cyverse-cli` image, I see that the auth functions of the CLI aren't working. Specifically, it appears the mechanism used to read values from the `~/.agave/current cache` don't work.

**To Reproduce**

Inside the container, `auth-tokens-refresh -S ` will fail with a stack trace, while it works outside the container. The `curl` command being sent inside the container is `curl -sku ":XXXXXX" -X POST -d "grant_type=refresh_token&refresh_token=&scope=PRODUCTION" -H "Content-Type:application/x-www-form-urlencoded" https://agave.iplantc.org/token` 

Notice that the `client` is missing from the HTTP Basic Auth parameter. Repeating with `auth-tokens-create -S` reveals that NONE of the variables are being pulled into the CLI runtime. 

`Calling curl -sku ":XXXXX" -X POST --data-urlencode "username=" --data-urlencode "password=XXXXX" --data-urlencode "grant_type=password" --data-urlencode "scope=PRODUCTION" -H "Content-Type:application/x-www-form-urlencoded" https://agave.iplantc.org/token
`

**Comment by deardooley** [comment]
I didn’t build the cyverse cli image, but my guess would be that you don’t have python installed in that container and that it’s not using the json-mirror api for json formatting. I suggest installing jq in the container and specifying that as the json parsing engine.

—
Rion

**Comment by mwvaughn** [comment]
Fixed. I had some subtle pathing issues to resolve.
